### PR TITLE
New sourforge.net link.

### PR DESCRIPTION
**Pull request by rasapala**
bintray will be EOLed 1st of May.
Switch to sourceforge.net because they do not have another link.

### CODE REVIEW

**Review by Ficol — APPROVED** [review]

**Review by atobiszei — COMMENTED** [review]
Why this change is needed and why we switch from original boost website download links?

**Comment by rasapala** [comment]
We need to change because the old links will be removed and not available anymore.

**Comment by atobiszei** [comment]
> We need to change because the old links will be removed and not available anymore.

Ok now I see that bintray will be EOLed 1st of May. Is the new binary download source officially confirmed?

The only information I found is here:
https://www.gitmemory.com/issue/boostorg/boost/499/809540576

That they are working on solution and plan to announce it on official webpage.

**Comment by rasapala** [comment]
Yeah not confirmed we should not wait until its confirmed and find a workaround in the meantime.

**Review by atobiszei — APPROVED** [review]
Ok, please explain situation in commit comment.

**Comment by rasapala** [comment]
bintray will be EOLed 1st of May.
Switch to sourceforge.net because they do not have another link.

**Pull request merged**
