### PR TITLE
added instructions for a simple endpoint test

### PR DESCRIPTION
**Pull request by dtrawins**

### CODE REVIEW

**Review by rasapala — APPROVED** [review]
LGTM

**Review by ryanloney — APPROVED** [review]
I would like to test this, but creating a ModelServer instance on the internal cluster does not work for me. Fine to merge it though, so we have some instructions to test if the service is up.

**Comment by ryanloney** [comment]
Ignore my previous comment. I needed to set the proxy. It works as expected. 

image

**Comment by ryanloney** [comment]
@rasapala can we please merge this?

**Pull request merged**
